name: .NET

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags, e.g., v1.0.0
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Pack the NuGet package
      run: dotnet pack --configuration Release --output ./nupkg

    - name: Add GitHub as source
      run: dotnet nuget add source --name github "https://nuget.pkg.github.com/maxnau/index.json" --username maxnau --password ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to GitHub Packages
      run: dotnet nuget push ./nupkg/*.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}
